-- Custom Auth Helper Functions for Better Auth JWT
-- Extracts user_id (TEXT) from JWT token generated by Better Auth

-- Function to get current user ID from JWT token
-- Returns TEXT since Better Auth uses TEXT user IDs
CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS TEXT AS $$
BEGIN
  -- Extract the 'sub' claim from the JWT token
  -- This works with the custom JWT tokens created in supabase-token.ts
  RETURN (SELECT auth.jwt()->>'sub');
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- Set search path to avoid ambiguity
ALTER FUNCTION public.current_user_id() SET search_path = auth, public;

COMMENT ON FUNCTION public.current_user_id() IS 'Returns the current authenticated user ID from the JWT sub claim (Better Auth integration)';

-- Function to check meeting access without triggering recursive RLS policy evaluation
CREATE OR REPLACE FUNCTION public.can_access_meeting(
  p_meeting_id UUID,
  p_user_id TEXT
)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM "public"."meeting" m
    WHERE m.id = p_meeting_id
      AND (
        m.creator_id = p_user_id
        OR EXISTS (
          SELECT 1
          FROM "public"."meeting_participant" mp
          WHERE mp.meeting_id = p_meeting_id
            AND mp.user_id = p_user_id
        )
      )
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

ALTER FUNCTION public.can_access_meeting(UUID, TEXT) SET search_path = public;

COMMENT ON FUNCTION public.can_access_meeting(UUID, TEXT) IS 'Checks whether a user can access a meeting (creator or participant) without recursive RLS policy evaluation';
